import {FormEvent,useEffect,useState} from 'react'; import {api} from './api';
type Crate={id:number;code:string;name:string;location:string;cleaning_status:string;active:boolean;isolated:boolean};
type Issue={id:number;crate_code:string;crate_name:string;issue_type:string;occurred_at:string;reason:string;status:string};
const labels:Record<string,string>={clean:'已清洁',dirty:'待清洗',unknown:'未知',reuse_without_wash:'未清洗再次领用',use_while_isolated:'已隔离仍领用',expired_inspection:'检查已过期',pending:'待处理',confirmed:'已确认',false_positive:'误报',closed:'已关闭'};
export default function App(){
 const [tab,setTab]=useState('home'),[crates,setCrates]=useState<Crate[]>([]),[issues,setIssues]=useState<Issue[]>([]),[metrics,setMetrics]=useState<Record<string,number>>({}),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 const [filter,setFilter]=useState({code:'',location:'',cleaning_status:'',status:''});
 const load=async()=>{setLoading(true);try{const [c,i,d]=await Promise.all([api(`/crates?code=${filter.code}&location=${filter.location}&cleaning_status=${filter.cleaning_status}`),api(`/issues?crate_code=${filter.code}&status=${filter.status}`),api('/dashboard')]);setCrates(c);setIssues(i);setMetrics(d)}catch(e){setMsg((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[filter]);
 const submitCrate=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api('/crates',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});form.reset();setMsg('周转箱新增成功');load()}catch(e){setMsg((e as Error).message)}};
 const submitEvent=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api('/events',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});form.reset();setMsg('流转事件登记成功');load()}catch(e){setMsg((e as Error).message)}};
 const resolve=async(id:number,status:string)=>{const note=prompt('处理说明（可留空）')||'';try{await api(`/issues/${id}`,{method:'PATCH',body:JSON.stringify({status,resolution_note:note})});setMsg('问题状态更新成功');load()}catch(e){setMsg((e as Error).message)}};
 return <><header><div><span className="logo">箱</span><b>周转箱清洁追溯平台</b><small> 食品工厂安全运营</small></div><nav>{[['home','总览'],['crates','周转箱'],['events','登记流转'],['issues','问题中心']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav></header><main>{msg&&<div className={msg.includes('成功')?'toast ok':'toast'}>{msg}</div>}{loading?<div className="loading">正在加载数据…</div>:<>
 {tab==='home'&&<><section className="hero"><div><p>今日运营概览</p><h1>让每一个周转箱<br/>都清洁、可追溯</h1><span>实时掌握箱体状态，提前发现食品安全隐患。</span></div><div className="ring">{metrics.active_crates}<small>在用箱体</small></div></section><section className="metrics">{[['周转箱总数',metrics.total_crates],['清洁可用',metrics.clean_crates],['待处理问题',metrics.pending_issues],['隔离箱体',metrics.isolated_crates]].map((x,i)=><article key={String(x[0])} className={'m'+i}><span>{x[0]}</span><strong>{x[1]||0}</strong></article>)}</section><Panel title="最新风险"><IssueTable issues={issues.slice(0,5)} resolve={resolve}/></Panel></>}
 {tab==='crates'&&<><Filters filter={filter} setFilter={setFilter}/><div className="split"><Panel title="周转箱台账"><div className="cards">{crates.map(c=><article className="crate" key={c.id}><div><b>{c.code}</b><em className={c.cleaning_status}>{labels[c.cleaning_status]}</em></div><h3>{c.name}</h3><p>📍 {c.location}</p><small>{c.active?'在用':'已停用'}{c.isolated?' · 已隔离':''}</small><div className="actions"><button onClick={async()=>{const location=prompt('新的当前位置',c.location);if(location){await api(`/crates/${c.id}`,{method:'PUT',body:JSON.stringify({location})});setMsg('周转箱编辑成功');load()}}}>编辑位置</button>{c.active&&<button onClick={async()=>{await api(`/crates/${c.id}/deactivate`,{method:'POST'});setMsg('周转箱已停用');load()}}>停用</button>}</div></article>)}</div></Panel><Panel title="新增周转箱"><form onSubmit={submitCrate}><Input name="code" label="唯一编号"/><Input name="name" label="名称"/><Input name="location" label="当前位置"/><label>清洁状态<select name="cleaning_status"><option value="unknown">未知</option><option value="clean">已清洁</option><option value="dirty">待清洗</option></select></label><label>备注<textarea name="notes"/></label><button className="primary">保存周转箱</button></form></Panel></div></>}
 {tab==='events'&&<Panel title="登记流转事件"><form className="event-form" onSubmit={submitEvent}><Input name="event_no" label="事件编号"/><Input name="crate_code" label="周转箱编号"/><label>事件类型<select name="event_type">{[['inbound','入库'],['issue','领用'],['return','归还'],['wash','清洗'],['inspect','检查'],['isolate','隔离']].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>发生时间<input name="occurred_at" type="datetime-local" required/></label><Input name="operator" label="操作人"/><label>说明<textarea name="description"/></label><button className="primary">提交事件</button></form></Panel>}
 {tab==='issues'&&<><Filters filter={filter} setFilter={setFilter} issues/><Panel title="问题清单"><IssueTable issues={issues} resolve={resolve}/></Panel></>}</>}</main></>}
function Panel(p:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{p.title}</h2>{p.children}</section>}; function Input({name,label,...rest}:{name:string;label:string;[key:string]:unknown}){return <label>{label}<input name={name} required {...rest}/></label>}
function Filters({filter,setFilter,issues}:{filter:any;setFilter:any;issues?:boolean}){return <div className="filters"><input placeholder="按编号筛选" value={filter.code} onChange={e=>setFilter({...filter,code:e.target.value})}/>{!issues&&<><input placeholder="按位置筛选" value={filter.location} onChange={e=>setFilter({...filter,location:e.target.value})}/><select value={filter.cleaning_status} onChange={e=>setFilter({...filter,cleaning_status:e.target.value})}><option value="">全部清洁状态</option><option value="clean">已清洁</option><option value="dirty">待清洗</option></select></>}{issues&&<select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">全部问题状态</option>{['pending','confirmed','false_positive','closed'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select>}</div>}
function IssueTable({issues,resolve}:{issues:Issue[];resolve:(id:number,status:string)=>void}){return <div className="table"><table><thead><tr><th>周转箱</th><th>问题类型</th><th>发生时间</th><th>原因</th><th>状态</th><th>处理</th></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td><b>{i.crate_code}</b><br/><small>{i.crate_name}</small></td><td>{labels[i.issue_type]}</td><td>{new Date(i.occurred_at).toLocaleString()}</td><td>{i.reason}</td><td><em>{labels[i.status]}</em></td><td><select value={i.status} onChange={e=>resolve(i.id,e.target.value)}>{['pending','confirmed','false_positive','closed'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></td></tr>)}</tbody></table>{!issues.length&&<p className="empty">暂无符合条件的问题</p>}</div>}
