import {FormEvent,useEffect,useRef,useState} from 'react'; import {api} from './api';
type Crate={id:number;code:string;name:string;location:string;cleaning_status:string;active:boolean;isolated:boolean;backup_code?:string|null};
type Issue={id:number;crate_code:string;crate_name:string;issue_type:string;occurred_at:string;reason:string;status:string;rectification_event_no?:string|null};
type PlanItem={crate_id:number;code:string;name:string;location:string;last_inspected_at:string|null;due_date:string|null;days_remaining:number|null;category:string};
type InvCheck={id:number;location:string;status:string;created_at:string;completed_at:string|null;expected:string[];scanned:string[];missing:string[];misplaced:{crate_code:string;location:string}[]};
const labels:Record<string,string>={clean:'已清洁',dirty:'待清洗',unknown:'未知',reuse_without_wash:'未清洗再次领用',use_while_isolated:'已隔离仍领用',expired_inspection:'检查已过期',pending:'待处理',confirmed:'已确认',false_positive:'误报',closed:'已关闭'};
const planLabels:Record<string,string>={never_inspected:'从未检查',overdue:'已过期',due_soon:'即将到期'};
const etypes=[['inbound','入库'],['issue','领用'],['return','归还'],['wash','清洗'],['inspect','检查'],['isolate','隔离']];
export default function App(){
 const [tab,setTab]=useState('home'),[crates,setCrates]=useState<Crate[]>([]),[issues,setIssues]=useState<Issue[]>([]),[metrics,setMetrics]=useState<Record<string,number>>({}),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 const [filter,setFilter]=useState({code:'',location:'',cleaning_status:'',status:''});
 const [emode,setEmode]=useState('single'),[codes,setCodes]=useState<string[]>([]),[codeInput,setCodeInput]=useState(''),[pasteText,setPasteText]=useState(''),[batchRes,setBatchRes]=useState<{crate_code:string;event_no:string}[]|null>(null),[batchBusy,setBatchBusy]=useState(false);
 const [planBase,setPlanBase]=useState(()=>new Date().toISOString().slice(0,10)),[planDays,setPlanDays]=useState('7'),[plan,setPlan]=useState<PlanItem[]|null>(null),[planValid,setPlanValid]=useState(30),[planErr,setPlanErr]=useState(''),[planLoading,setPlanLoading]=useState(false);
 const [prefill,setPrefill]=useState<{crate_code:string;event_type:string;occurred_at:string;issue_id?:number;from?:string}|null>(null),[prefillKey,setPrefillKey]=useState(0);
 const [invLocations,setInvLocations]=useState<string[]>([]),[invLocation,setInvLocation]=useState(''),[invCheck,setInvCheck]=useState<InvCheck|null>(null),[invScans,setInvScans]=useState<string[]>([]),[invScanInput,setInvScanInput]=useState(''),[invHistory,setInvHistory]=useState<InvCheck[]>([]),[invReview,setInvReview]=useState<InvCheck|null>(null),[invBusy,setInvBusy]=useState(false);
 const batchBusyRef=useRef(false),invBusyRef=useRef(false);
 const load=async()=>{setLoading(true);try{const [c,i,d]=await Promise.all([api(`/crates?code=${filter.code}&location=${filter.location}&cleaning_status=${filter.cleaning_status}`),api(`/issues?crate_code=${filter.code}&status=${filter.status}`),api('/dashboard')]);setCrates(c);setIssues(i);setMetrics(d)}catch(e){setMsg((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[filter]);
 const loadPlan=async()=>{setPlanErr('');
  if(!planBase){setPlanErr('请选择基准日期后再查询');return}
  const days=Number(planDays);
  if(planDays.trim()===''||!Number.isInteger(days)||days<0||days>365){setPlanErr('未来天数需为 0 至 365 的整数，请修正后重新查询');return}
  setPlanLoading(true);
  try{const r=await api(`/inspection-plan?base_date=${planBase}&days_ahead=${days}`);setPlan(r.items);setPlanValid(r.valid_days)}catch(e){const err=e as Error&{status?:number};setPlanErr(err.status===422?'基准日期或未来天数不合法，请修正后重新查询':`查询失败：${err.message}`)}finally{setPlanLoading(false)}};
 useEffect(()=>{if(tab==='plan'&&!plan&&!planErr)loadPlan()},[tab]);
 const loadInv=async()=>{try{const [checks,active]=await Promise.all([api('/inventory-checks'),api('/crates?active=true')]);setInvHistory(checks);setInvLocations([...new Set<string>(active.map((c:Crate)=>c.location))].sort())}catch(e){setMsg((e as Error).message)}};
 useEffect(()=>{if(tab==='inventory')loadInv()},[tab]);
 const startCheck=async()=>{if(!invLocation)return;try{const c=await api('/inventory-checks',{method:'POST',body:JSON.stringify({location:invLocation})});setInvCheck(c);setInvScans([]);setInvScanInput('');setInvReview(null);setMsg(`盘点单创建成功：库位 ${c.location} 应在 ${c.expected.length} 箱，请逐个扫描箱号后提交`);loadInv()}catch(e){setMsg((e as Error).message)}};
 const addScan=(raw:string)=>{const parts=raw.split(/[\s,，、;；]+/).map(s=>s.trim()).filter(Boolean);if(parts.length)setInvScans(s=>[...s,...parts])};
 const invDups=[...new Set(invScans.filter((x,i)=>invScans.indexOf(x)!==i))];
 const submitCheck=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!invCheck||invBusyRef.current)return;
  if(!invScans.length){setMsg('请先扫描或录入箱号');return}
  if(invDups.length){setMsg(`存在重复箱号，请修正后再提交：${invDups.join('、')}`);return}
  invBusyRef.current=true;setInvBusy(true);
  // 失败时保留已扫描内容，修正后可再次提交
  try{const c=await api(`/inventory-checks/${invCheck.id}/complete`,{method:'POST',body:JSON.stringify({scanned_codes:invScans})});setInvCheck(null);setInvScans([]);setInvScanInput('');setInvReview(c);setMsg(`盘点完成：应在 ${c.expected.length} 箱，实扫 ${c.scanned.length} 箱，缺失 ${c.missing.length} 箱，错放 ${c.misplaced.length} 箱`);loadInv()}catch(e){setMsg((e as Error).message)}finally{invBusyRef.current=false;setInvBusy(false)}};
 const resumeCheck=(c:InvCheck)=>{setInvCheck(c);setInvScans([]);setInvScanInput('');setInvReview(null);setMsg(`继续盘点单 #${c.id}：库位 ${c.location} 应在 ${c.expected.length} 箱，请逐个扫描箱号后提交`)};
 const registerInspection=(p:PlanItem)=>{setPrefill({crate_code:p.code,event_type:'inspect',occurred_at:`${planBase}T09:00`,from:'plan'});setPrefillKey(k=>k+1);setEmode('single');setTab('events');setMsg(`已为周转箱 ${p.code} 预填检查单，请补齐事件编号与操作人后提交`)};
 const registerRectification=(i:Issue)=>{
  const event_type=i.issue_type==='reuse_without_wash'?'wash':'inspect';
  const advice=event_type==='wash'?'清洗':'检查';
  setPrefill({crate_code:i.crate_code,event_type,occurred_at:new Date().toISOString().slice(0,16),issue_id:i.id,from:'issue'});
  setPrefillKey(k=>k+1);setEmode('single');setTab('events');
  setMsg(`已按整改建议为周转箱 ${i.crate_code} 预填${advice}单，请补齐事件编号、时间与操作人后提交`);
 };
 const submitCrate=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api('/crates',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});form.reset();setMsg('周转箱新增成功');load()}catch(e){setMsg((e as Error).message)}};
 const bindBackup=async(c:Crate)=>{const backup_code=(prompt('备用编号（破损标签更换后的新编号）',c.backup_code||'')||'').trim();if(!backup_code)return;try{await api(`/crates/${c.id}/backup-code`,{method:'POST',body:JSON.stringify({backup_code})});setMsg(`备用编号绑定成功，登记时输入 ${backup_code} 将解析到 ${c.code}`);load()}catch(e){setMsg((e as Error).message)}};
 const submitEvent=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),fromIssue=prefill?.issue_id!==undefined,fromPlan=prefill?.from==='plan';
  const payload:Record<string,unknown>=Object.fromEntries(f);
  if(fromIssue)payload.issue_id=prefill!.issue_id;
  try{await api('/events',{method:'POST',body:JSON.stringify(payload)});setPrefill(null);setPrefillKey(k=>k+1);setMsg(fromIssue?'整改登记成功，问题已关闭':'流转事件登记成功');load();if(plan)loadPlan();if(fromIssue)setTab('issues');else if(fromPlan)setTab('plan')}catch(e){setMsg((e as Error).message)}};
 const addCodes=(raw:string)=>{const parts=raw.split(/[\s,，、;；]+/).map(s=>s.trim()).filter(Boolean);if(parts.length)setCodes(c=>[...c,...parts])};
 const dups=[...new Set(codes.filter((x,i)=>codes.indexOf(x)!==i))];
 const submitBatch=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(batchBusyRef.current)return;const form=e.currentTarget,f=new FormData(form);
  if(!codes.length){setMsg('请先逐项录入或粘贴箱号');return}
  if(dups.length){setMsg(`存在重复箱号，请修正后再提交：${dups.join('、')}`);return}
  batchBusyRef.current=true;setBatchBusy(true);
  try{const r=await api('/events/batch',{method:'POST',body:JSON.stringify({batch_no:f.get('batch_no'),event_type:f.get('event_type'),occurred_at:f.get('occurred_at'),operator:f.get('operator'),description:f.get('description')||'',crate_codes:codes})});setBatchRes(r.results);form.reset();setCodes([]);setPasteText('');setCodeInput('');setMsg(`批量登记成功，共${r.results.length}箱`);load()}catch(e){setBatchRes(null);setMsg((e as Error).message)}finally{batchBusyRef.current=false;setBatchBusy(false)}};
 const resolve=async(id:number,status:string)=>{const note=prompt('处理说明（可留空）')||'';try{await api(`/issues/${id}`,{method:'PATCH',body:JSON.stringify({status,resolution_note:note})});setMsg('问题状态更新成功');load()}catch(e){setMsg((e as Error).message)}};
 return <><header><div><span className="logo">箱</span><b>周转箱清洁追溯平台</b><small> 食品工厂安全运营</small></div><nav>{[['home','总览'],['plan','检查计划'],['inventory','库位盘点'],['crates','周转箱'],['events','登记流转'],['issues','问题中心']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav></header><main>{msg&&<div className={msg.includes('成功')||msg.includes('预填')||msg.includes('盘点完成')||msg.includes('继续盘点')?'toast ok':'toast'}>{msg}</div>}{loading?<div className="loading">正在加载数据…</div>:<>
 {tab==='home'&&<><section className="hero"><div><p>今日运营概览</p><h1>让每一个周转箱<br/>都清洁、可追溯</h1><span>实时掌握箱体状态，提前发现食品安全隐患。</span><button className="hero-cta" onClick={()=>setTab('plan')}>进入检查计划</button></div><div className="ring">{metrics.active_crates}<small>在用箱体</small></div></section><section className="metrics">{[['周转箱总数',metrics.total_crates],['清洁可用',metrics.clean_crates],['待处理问题',metrics.pending_issues],['隔离箱体',metrics.isolated_crates]].map((x,i)=><article key={String(x[0])} className={'m'+i}><span>{x[0]}</span><strong>{x[1]||0}</strong></article>)}</section><Panel title="最新风险"><IssueTable issues={issues.slice(0,5)} resolve={resolve} rectify={registerRectification}/></Panel></>}
 {tab==='plan'&&<><div className="filters plan-filters"><label>基准日期<input type="date" value={planBase} onChange={e=>setPlanBase(e.target.value)}/></label><label>未来天数<input type="number" min={0} max={365} step={1} value={planDays} onChange={e=>setPlanDays(e.target.value)}/></label><button onClick={loadPlan} disabled={planLoading}>查询</button></div>{planErr&&<p className="warn plan-err" role="alert">{planErr}</p>}<Panel title={`检查计划 · 检查有效期 ${planValid} 天`}>{planLoading?<p className="empty">正在查询检查计划…</p>:plan?<div className="table"><table><thead><tr><th>分类</th><th>箱号</th><th>名称</th><th>位置</th><th>最近检查</th><th>到期日</th><th>剩余天数</th><th>操作</th></tr></thead><tbody>{plan.map(p=><tr key={p.code}><td><em className={p.category}>{planLabels[p.category]}</em></td><td><b>{p.code}</b></td><td>{p.name}</td><td>{p.location}</td><td>{p.last_inspected_at?new Date(p.last_inspected_at).toLocaleDateString():'—'}</td><td>{p.due_date||'—'}</td><td>{p.days_remaining===null?'—':p.days_remaining<0?`超期 ${-p.days_remaining} 天`:p.days_remaining===0?'今天到期':`剩 ${p.days_remaining} 天`}</td><td><button className="plan-btn" onClick={()=>registerInspection(p)}>登记检查</button></td></tr>)}</tbody></table>{!plan.length&&<p className="empty">当前窗口内没有需要检查的周转箱</p>}</div>:<p className="empty">请选择基准日期与未来天数后查询</p>}</Panel></>}
 {tab==='inventory'&&<><div className="filters inv-filters"><label>盘点库位<select value={invLocation} onChange={e=>setInvLocation(e.target.value)}><option value="">请选择库位</option>{invLocations.map(l=><option key={l} value={l}>{l}</option>)}</select></label><button onClick={startCheck} disabled={!invLocation}>开始盘点</button></div>
 {invCheck&&<Panel title={`盘点中 · 库位 ${invCheck.location} · 应在 ${invCheck.expected.length} 箱`}><div className="chips inv-expected">{invCheck.expected.map(c=><span className="chip" key={c}>{c}</span>)}</div><form className="event-form" onSubmit={submitCheck}><label>扫描箱号（主编号或备用编号）<input placeholder="扫描或输入箱号后回车" value={invScanInput} onChange={e=>setInvScanInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addScan(invScanInput);setInvScanInput('')}}}/></label><button type="button" className="inline" onClick={()=>{addScan(invScanInput);setInvScanInput('')}}>添加箱号</button>{invDups.length>0&&<p className="warn">重复箱号：{invDups.join('、')}（提交前请修正）</p>}{invScans.length>0&&<div className="chips">{invScans.map((c,i)=><span className="chip" key={i}>{c}<button type="button" title="移除" onClick={()=>setInvScans(invScans.filter((_,j)=>j!==i))}>×</button></span>)}</div>}<button className="primary" disabled={invBusy}>提交盘点（{invScans.length}箱）</button></form></Panel>}
 {invReview&&<Panel title={`盘点结果 · 库位 ${invReview.location}${invReview.completed_at?' · '+new Date(invReview.completed_at).toLocaleString():''}`}><InvResult check={invReview}/></Panel>}
 <Panel title="盘点记录"><div className="table"><table><thead><tr><th>单号</th><th>库位</th><th>创建时间</th><th>状态</th><th>应在/实扫/缺失/错放</th><th>操作</th></tr></thead><tbody>{invHistory.map(c=><tr key={c.id}><td>#{c.id}</td><td>{c.location}</td><td>{new Date(c.created_at).toLocaleString()}</td><td><em>{c.status==='completed'?'已完成':'进行中'}</em></td><td>{c.expected.length}/{c.scanned.length}/{c.missing.length}/{c.misplaced.length}</td><td>{c.status==='completed'?<button className="plan-btn" onClick={()=>setInvReview(c)}>复看结果</button>:<button className="plan-btn" onClick={()=>resumeCheck(c)}>继续盘点</button>}</td></tr>)}</tbody></table>{!invHistory.length&&<p className="empty">暂无盘点记录</p>}</div></Panel></>}
 {tab==='crates'&&<><Filters filter={filter} setFilter={setFilter}/><div className="split"><Panel title="周转箱台账"><div className="cards">{crates.map(c=><article className="crate" key={c.id}><div><b>{c.code}</b><em className={c.cleaning_status}>{labels[c.cleaning_status]}</em></div><h3>{c.name}</h3><p>📍 {c.location}</p><small>{c.active?'在用':'已停用'}{c.isolated?' · 已隔离':''}</small>{c.backup_code&&<small>备用编号：{c.backup_code}</small>}<div className="actions"><button onClick={()=>bindBackup(c)}>绑定备用编号</button><button onClick={async()=>{const location=prompt('新的当前位置',c.location);if(location){await api(`/crates/${c.id}`,{method:'PUT',body:JSON.stringify({location})});setMsg('周转箱编辑成功');load()}}}>编辑位置</button>{c.active&&<button onClick={async()=>{await api(`/crates/${c.id}/deactivate`,{method:'POST'});setMsg('周转箱已停用');load()}}>停用</button>}</div></article>)}</div></Panel><Panel title="新增周转箱"><form onSubmit={submitCrate}><Input name="code" label="唯一编号"/><Input name="name" label="名称"/><Input name="location" label="当前位置"/><label>清洁状态<select name="cleaning_status"><option value="unknown">未知</option><option value="clean">已清洁</option><option value="dirty">待清洗</option></select></label><label>备注<textarea name="notes"/></label><button className="primary">保存周转箱</button></form></Panel></div></>}
 {tab==='events'&&<><div className="filters"><button className={emode==='single'?'active':''} onClick={()=>setEmode('single')}>单笔登记</button><button className={emode==='batch'?'active':''} onClick={()=>setEmode('batch')}>批量模式</button></div>
 {emode==='single'&&<Panel title="登记流转事件"><form key={prefillKey} className="event-form" onSubmit={submitEvent}>{prefill?.issue_id!==undefined&&<input type="hidden" name="issue_id" value={prefill.issue_id}/>}<Input name="event_no" label="事件编号"/><Input name="crate_code" label="周转箱编号" defaultValue={prefill?.crate_code||''}/><label>事件类型<select name="event_type" defaultValue={prefill?.event_type||'inbound'}>{etypes.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>发生时间<input name="occurred_at" type="datetime-local" defaultValue={prefill?.occurred_at||''} required/></label><Input name="operator" label="操作人"/><label>说明<textarea name="description"/></label><button className="primary">提交事件</button></form></Panel>}
 {emode==='batch'&&<><Panel title="批量登记流转"><form className="event-form" onSubmit={submitBatch}><Input name="batch_no" label="批次编号"/><label>事件类型<select name="event_type">{etypes.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>发生时间<input name="occurred_at" type="datetime-local" required/></label><Input name="operator" label="操作人"/><label>说明<textarea name="description"/></label><label>逐项录入箱号<input placeholder="输入箱号后点击添加" value={codeInput} onChange={e=>setCodeInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addCodes(codeInput);setCodeInput('')}}}/></label><button type="button" className="inline" onClick={()=>{addCodes(codeInput);setCodeInput('')}}>添加箱号</button><label>粘贴箱号（每行一个，或用逗号/空格分隔）<textarea placeholder={'BX-001\nBX-002\nBX-003'} value={pasteText} onChange={e=>setPasteText(e.target.value)}/></label><button type="button" className="inline" onClick={()=>{addCodes(pasteText);setPasteText('')}}>解析并添加</button>{dups.length>0&&<p className="warn">重复箱号：{dups.join('、')}（提交前请修正）</p>}{codes.length>0&&<div className="chips">{codes.map((c,i)=><span className="chip" key={i}>{c}<button type="button" title="移除" onClick={()=>setCodes(codes.filter((_,j)=>j!==i))}>×</button></span>)}</div>}<button className="primary" disabled={batchBusy}>提交批量事件（{codes.length}箱）</button></form></Panel>
 {batchRes&&<Panel title="批量处理结果"><div className="table"><table><thead><tr><th>#</th><th>箱号</th><th>事件编号</th><th>处理结果</th></tr></thead><tbody>{batchRes.map((r,i)=><tr key={r.event_no}><td>{i+1}</td><td><b>{r.crate_code}</b></td><td>{r.event_no}</td><td><em>登记成功</em></td></tr>)}</tbody></table></div></Panel>}</>}</>}
 {tab==='issues'&&<><Filters filter={filter} setFilter={setFilter} issues/><Panel title="问题清单"><IssueTable issues={issues} resolve={resolve} rectify={registerRectification}/></Panel></>}</>}</main></>}
function Panel(p:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{p.title}</h2>{p.children}</section>}; function Input({name,label,...rest}:{name:string;label:string;[key:string]:unknown}){return <label>{label}<input name={name} required {...rest}/></label>}
function InvResult({check}:{check:InvCheck}){const groups:[string,string[]][]=[['应在',check.expected],['实扫',check.scanned],['缺失',check.missing]];
 return <div className="inv-result">{groups.map(([t,list])=><section key={t}><h3>{t}（{list.length}）</h3>{list.length?<div className="chips">{list.map(c=><span className="chip" key={c}>{c}</span>)}</div>:<p className="empty">无</p>}</section>)}<section><h3>错放（{check.misplaced.length}）</h3>{check.misplaced.length?<div className="chips">{check.misplaced.map(m=><span className="chip" key={m.crate_code}>{m.crate_code}<small>（登记位置：{m.location}）</small></span>)}</div>:<p className="empty">无</p>}</section></div>}
function Filters({filter,setFilter,issues}:{filter:any;setFilter:any;issues?:boolean}){return <div className="filters"><input placeholder="按编号筛选" value={filter.code} onChange={e=>setFilter({...filter,code:e.target.value})}/>{!issues&&<><input placeholder="按位置筛选" value={filter.location} onChange={e=>setFilter({...filter,location:e.target.value})}/><select value={filter.cleaning_status} onChange={e=>setFilter({...filter,cleaning_status:e.target.value})}><option value="">全部清洁状态</option><option value="clean">已清洁</option><option value="dirty">待清洗</option></select></>}{issues&&<select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">全部问题状态</option>{['pending','confirmed','false_positive','closed'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select>}</div>}
function IssueTable({issues,resolve,rectify}:{issues:Issue[];resolve:(id:number,status:string)=>void;rectify:(i:Issue)=>void}){return <div className="table"><table><thead><tr><th>周转箱</th><th>问题类型</th><th>发生时间</th><th>原因</th><th>状态</th><th>处理</th></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td><b>{i.crate_code}</b><br/><small>{i.crate_name}</small></td><td>{labels[i.issue_type]}</td><td>{new Date(i.occurred_at).toLocaleString()}</td><td>{i.reason}{i.rectification_event_no&&<><br/><small className="linked">整改事件：{i.rectification_event_no}</small></>}</td><td><em>{labels[i.status]}</em></td><td><select value={i.status} onChange={e=>resolve(i.id,e.target.value)}>{['pending','confirmed','false_positive','closed'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select>{i.status==='confirmed'&&<button className="plan-btn" onClick={()=>rectify(i)}>登记整改</button>}</td></tr>)}</tbody></table>{!issues.length&&<p className="empty">暂无符合条件的问题</p>}</div>}
